[versions]
gradle-starter = "0.59.0"
gradle-pluginpublish = "1.2.0"
gradle-doctor = "0.8.1"
google-agp = "7.4.2"
maven-junit = "5.9.2"
maven-assertj = "3.24.2"
maven-ktlint = "0.48.2"
maven-commons = "2.11.0"

[libraries]
agp-gradle = { module = "com.android.tools.build:gradle", version.ref = "google-agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin" }
ktlint-core = { module = "com.pinterest.ktlint:ktlint-core", version.ref = "maven-ktlint" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "maven-junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "maven-junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "maven-assertj" }
commons-io = { module = "commons-io:commons-io", version.ref = "maven-commons" }

[plugins]
starter-config = { id = "com.starter.config", version.ref = "gradle-starter" }
starter-versioning = { id = "com.starter.versioning", version.ref = "gradle-starter" }
starter-library-kotlin = { id = "com.starter.library.kotlin", version.ref = "gradle-starter" }
gradle-pluginpublish = { id = "com.gradle.plugin-publish", version.ref = "gradle-pluginpublish" }
osacky-doctor = { id = "com.osacky.doctor", version.ref = "gradle-doctor" }
