name: Release Plugin

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update README.md content
        run: sed -i -E 's/version "[[:digit:]]+.[[:digit:]]+.[[:digit:]]+"/version "${{ github.event.release.tag_name }}"/g' README.md
        shell: bash

      - name: Create Readme version bump Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "Update Readme for the release ${{ github.event.release.tag_name }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: "Update Readme for the release ${{ github.event.release.tag_name }}"
          body: |
            Release: https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }}
